### ISSUE TITLE
[JS Rules] Function Confirmation

### ISSUE THREAD

**Issue by jhmullen** [Datawheel/codelife#180]
Check actual eval'd js for:
- Presence of a given function
- Arguments are of a proper type
- Arguments exactly match given value

This will likely need to be a combination of checking the contents of the code and also the state of the jsvm/page itself.  For example, the following need to be evaluated the same way:

```js
console.log("jimmy");
```

```js
var name = "jimmy";
console.log(name);
```

This can be accomplished by separating on commas with parens, giving a list of arguments as **strings**.  We then need to try a series of methods to test them:

- If the string has quotation marks in it, it's a string, and we can interpret the literal directly
- Otherwise, it may be a variable, so check the js vm state for that variable and its type
- Otherwise, it may be an expression, so eval it, and check the result's type and value.

**Comment by davelandry** [comment]
After doing a little bit of digging, you're probably going to have to do this in 2 steps. First, do a regex which returns the function name an all of the arguments inside of the parentheses:

```js
/(console.log)\((\s*([^)]+?)\s*)\)/g
```

Then, do a split on the argument string for all commas including any number of spaces after a comma:

```js
/\s*,\s*/g
```

**Comment by jhmullen** [comment]
There's a known issue here - how do we tell the difference between the invocation `myFunc(abc)` and the declaration `function myFunc(str)`?

cc @davelandry

**Comment by davelandry** [comment]
I gotchu @jhmullen. We need to use a regex negative lookahead... which aren't available in Javascript. So I put together a little function to reverse a string, which can be used with a regular javascript lookahead:

```js
const reverse = s => s.split("").reverse().join("");

const funcTest = (string, func) => {

  const regexp = new RegExp(`\\)\\s*([^(]*?)\\s*\\(${reverse(func)}(?!\\s*noitcnuf)`, "g");
  let match = regexp.exec(reverse(string));
  if (match) match = match.map(reverse);
  return match;

}

var match = funcTest("var num = 10;\nmyFunc(num);", "myFunc");
```

**Comment by jhmullen** [comment]
With the addition of the console.log catcher from #271 this rule should be ready to go, closing.
