### ISSUE TITLE
[JS Rules] Regex "uses"

### ISSUE THREAD

**Issue by jhmullen** [Datawheel/codelife#182]
Check the non-eval'd, straight-up js code for the presence and structure of certain code elements, including:

- [ ] while
- [x] if / else
- [ ] function
- [x] for
- [ ] + - / * %

**Comment by davelandry** [comment]
Regex for detecting a function, with anything inside of the parentheses, and curly bracket enclosures:

```js
/while\s*\([^\)]*\)\s*{[^}]*}/g
```

Regex for detecting an operator:

```js
/\+/g
```

Regex for detecting an operator and returning the two surrounding variables:

```js
/([A-zÀ-ÿ0-9]+)\s*\+\s*([A-zÀ-ÿ0-9]+)/g
```

**Comment by jhmullen** [comment]
This currently works for `if`, `for`, and a user-given wildcard.  Currently deciding how strict to be on +/- operators

**Comment by jhmullen** [comment]
On revisiting this, +/- doesn't really fit JS_USES as a concept - JS_USES is for parenthetical function definitions of the type `name( ){ }`.

To catch operators, we should just use JS_MATCHES and write the operator manually.

We will likely be revisiting rules as more lessons come down the pipeline.
