### ISSUE TITLE
Fix loose attribute rule

### ISSUE THREAD

**Issue by jhmullen** [Datawheel/codelife#211]
Originally when checking for open and close tags, we used a simple string match for `<needle>` and `</needle>`.  However, now that we are including attributes, it really needs to be `<needle arbitrary="stuff" goes="here">` and `</needle>`

We currently use the simplistic path of just checking for `<needle` with no closing tag.  Enhance this to have a wildcard/regex in the middle, a la `<needle ???>`

- [x] contains
- [x] contains_self_close
- [x] contains_one
- [x] nests

**Comment by davelandry** [comment]
Unless I'm forgetting some exceptions, the basic regex to locate a tag with any number of characters inside the angle brackets EXCEPT for a right angle bracket would be:

```js
/<a[^>]*>/g
```
