### ISSUE TITLE
add hard stop after first island completion that requests user's school

### ISSUE THREAD

**Issue by davelandry** [Datawheel/codelife#212]
When a student enters any island other than the first island, a popup dialog should appear that asks the user for their school. It should not be closable, and it should not appear if the user has already set their school. 

- [x] @jhmullen implement "I'm not telling you" state
- [x] @jhmullen implement popup
- [x] @davelandry design

**Comment by jhmullen** [comment]
The implementation of this is in place.  @davelandry you can find the design elements in Checkpoint.jsx and SelectSchool.jsx, note that the latter is used in Profile.jsx so changes will propagate there.  

I use a special `-1` state school to indicate "choose not to answer."  Longer term, Checkpoint.jsx will be a more reusable json-fueled Interstitial.
