### ISSUE TITLE
Refresh console when navigating to a new slide

### ISSUE THREAD

**Issue by alexandersimoes** [Datawheel/codelife#226]
If there are two code example slides in a row with console messages, they get carried over from the previous slide. Example:

http://localhost:3300/island/island-900d/level-3071/slide-6b66
http://localhost:3300/island/island-900d/level-3071/slide-2226

**Comment by jhmullen** [comment]
This was actually fixed  by the "autoexecute" code of #210.  The console is cleared as part of an execute, and going to a new slide now freshly executes, clearing the console.  Two birds with one stone!
