### ISSUE TITLE
create featured CodeBlocks API route

### ISSUE THREAD

**Issue by davelandry** [Datawheel/codelife#228]
for now, just return the following CodeBlocks:
- 863
- 834
- 951
- 30

**Comment by jhmullen** [comment]
@davelandry 951 doesn't exist

**Comment by jhmullen** [comment]
I'm guessing that you meant 921, so I put that in.  I'm sending this back to you to confirm that's okay.

**Comment by jhmullen** [comment]
Access this by `/api/codeBlocks/featured`

**Comment by davelandry** [comment]
@jhmullen looks like 951 is only on the live "codelife" db, and not "codelifenov", it's from a student that signed up after we forked the db 😬

**Comment by davelandry** [comment]
closing as confirmed working
