### ISSUE TITLE
send admin e-mail when content is flagged

### ISSUE THREAD

**Issue by davelandry** [Datawheel/codelife#232]
In an ideal world, datawheel-canon would export a function that streamlines this process, but in the sprint world, here is the logic for how it's done: https://github.com/Datawheel/datawheel-canon/blob/master/src/auth/local.js#L109-L127

In essence, it's the following:
- initialize a Mailgun instance with the site's API key and domain (@alexandersimoes will be setting these up for #231)
- load in a template HTML file
- replace variables in that file (things like username and other specifics to the flagged content)
- send the e-mail!

**Comment by jhmullen** [comment]
This is in now and ready for QA.  We currently email on every Report to all admins, we can think on ways to adjust this later if this becomes unwieldy.

**Comment by jhmullen** [comment]
this has been in prod for a while now, closing.
