### ISSUE TITLE
implement social logout expiry from canon

### ISSUE THREAD

**Issue by davelandry** [Datawheel/codelife#237]
datawheel/datawheel-canon#38

**Comment by davelandry** [comment]
@alexandersimoes Logins will now, by default in datawheel-canon, expire after 1 hour. Everyone (including the server) needs to do an `npm i`.

If we want to change this on the site, we can set the following env var (time in ms):

```
export CANON_SESSION_TIMEOUT=3600000
```

**Comment by alexandersimoes** [comment]
Done.
