### ISSUE TITLE
fix blank toasts in locale JSON files

### ISSUE THREAD

**Issue by davelandry** [Datawheel/codelife#239]

**Comment by jhmullen** [comment]
I have filled in all the blank spots for mine, but I see new blank spots generated from @davelandry 's homepage.  I am bouncing this back to him as I'm not sure if anything special needs to be done or filled in his `home` object.

**Comment by davelandry** [comment]
home should be all set for now. those empty strings are actually from a similar named locale key inside of the datawheel-canon test app, and will be removed in a future update: https://github.com/Datawheel/datawheel-canon/issues/49
