### ISSUE TITLE
Industry Island

### ISSUE THREAD

**Issue by davelandry** [Datawheel/codelife#266]

**Comment by davelandry** [comment]
I have done my self-review pass and I'm handing the baton off to @alexandersimoes for his QA. Besides a couple of rules bugs that I have documented which prevent some of the tests from completing, we should be able to consider this island content complete!

**Comment by alexandersimoes** [comment]
Just did a QA test, cleaned up some text, fixed a few typos and modified one of the quizes but in general looks good to me. I did also notice those broken rules which will need to get fixed for this island to ship. Closing for now.
