### ISSUE TITLE
code gets rendered if there is no user-defined javascript

### ISSUE THREAD

**Issue by davelandry** [Datawheel/codelife#272]
happens whether or not there is a `<script>` tag present:

<img width="780" alt="screen shot 2017-11-02 at 1 22 37 pm" src="https://user-images.githubusercontent.com/1847581/32340550-4d4c0b04-bfd1-11e7-9a7b-8cfa353c7b4e.png">

**Comment by jhmullen** [comment]
I handle this by stripping spaces and newlines and using that to determine if there is anything worth executing, should be fixed now.
