### ISSUE TITLE
Hand-select Featured Projects and CodeBlocks

### ISSUE THREAD

**Issue by jhmullen** [Datawheel/codelife#273]
Which projects and codeblocks do you want featured?  

This currently blocks #227 and #228

**Comment by jhmullen** [comment]
Doh, nevermind.  I just realized @davelandry already filled out the ids like a good dooby.  Closing.

**Comment by davelandry** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/2c49e3e6-6f25-45a1-aeb8-b3296259c72f-3577108e-1ec2-48c9-96d2-36fa0c2c3b80-v1.png?transparent=1&palette=1&width=246)
