### ISSUE TITLE
Enable New "Lax Mode" on old slides, update DB on rel

### ISSUE THREAD

**Issue by jhmullen** [Datawheel/codelife#282]
Now that #194 has been closed, Editors need to go back through and Enable Lax Mode for early slides.

Note @alexandersimoes that this also means we'll need to make a db structure change to codelife release.  the `slides` table needs a new column named `lax` of type `boolean` with a default of `FALSE`

**Comment by davelandry** [comment]
@alexandersimoes this was completed by @jhmullen
