### ISSUE TITLE
[ post nov ] Create offline screenshot of codeblocks and projects

### ISSUE THREAD

**Issue by alexandersimoes** [Datawheel/codelife#284]
This might be long term but it would be great to have an offline script that renders student's HTML and creates a screenshot for us to then use as their icons, much like google docs does. I think we had thought about this before but i think it may have disappeared from our radar.

**Comment by davelandry** [comment]
Resurfacing #35 in lieu of this issue.

@alexandersimoes please don't mark issues with specific timeframes (ie. [ post nov ]). Anything not slated for the current sprint should be placed in the "Backlog" pipeline in ZenHub.
