### ISSUE TITLE
Make Share.jsx use remote execution

### ISSUE THREAD

**Issue by jhmullen** [Datawheel/codelife#295]
Replace Share.jsx's native iframe rendering with remote endpoint.  

This requires using CodeEditor's projectview mode, however this still shows the "Webpage" tag and console emulator.  Need to work with @davelandry  on stripping this out.

- [x] switch from iframe to codeeditor in share.jsx (jimmy)
- [x] restyle codeeditor to exclude "wepbage" bar and console emulator (dave)

**Comment by davelandry** [comment]
Also fixed with this commit: https://github.com/Datawheel/codelife/commit/25cba7d5a82f71fff164ec2927e58e819e6ee2f1
