### ISSUE TITLE
Adjust CSS on Lesson Builder

### ISSUE THREAD

**Issue by jhmullen** [Datawheel/codelife#323]
I fixed a bug on `develop` where surrounding a Quill editor in a `<label>` tag made the first toolbar element toggle itself on hover.  Here's the commit hash:  d7714c15ee8f34a645c93b247104354ab26a56ce

I have naively changed the label tag to a div, which fixes the problem in the fastest and dirtiest way, but now we have both divs and labels with the `pt-label` class.  This will need to be addressed with better CSS.

**Comment by davelandry** [comment]
everything looks okay to me. switching them from labels to divs didn't cause any noticeable change for me, and the CSS styles are still being applied (we just use classes).
