### ISSUE TITLE
add banner to all pages to indicate dev branch

### ISSUE THREAD

**Issue by alexandersimoes** [Datawheel/codelife#348]
Similar to what DataChile has done:

![screen shot 2018-02-12 at 9 59 01 am](https://user-images.githubusercontent.com/252276/36102836-892294d6-0fdb-11e8-8685-a65bae59588e.png)

It would be nice to have a banner saying you're viewing the staging/dev version of the site so that contributors don't accidentally add content and expect it to show up on the live site.

**Comment by alexandersimoes** [comment]
from manuel:

https://github.com/Datawheel/datachile/blob/master/app/components/App.jsx#L45

https://github.com/Datawheel/datachile/blob/master/app/components/StagingIndicator.jsx
and yeah, it's set by the `__STAGING__` and `__DEV__` global constants, which you can set as env vars`CANON_CONST_STAGING` and `CANON_CONST_DEV`, respectively

**Comment by jhmullen** [comment]
Put this in a while ago (though I did it differently than the canon constants)
