### ISSUE TITLE
make glossary content SEO friendly

### ISSUE THREAD

**Issue by alexandersimoes** [Datawheel/codelife#349]
Currently viewing source on the glossary page renders all the actual content in JS not as HTML which doesn't help us much with SEO. It would be great to add the fetch for glossary content as a preneed to happen server side and send this HTML to the front-end pre-rendered.

**Comment by davelandry** [comment]
@jhmullen what HTML is actually being delivered by the server? If it's the loading component, then my hunch is that you'll need to add another catch to `App.jsx` to allow the glossary page to pass through without needing the user to be defined.
