### ISSUE TITLE
unable to add new word to glossary

### ISSUE THREAD

**Issue by alexandersimoes** [Datawheel/codelife#350]
After clicking "add word" in the glossary admin section I am unable to edit the title aka the term.

Also, let's change nuevo palavra to "novo termo" on the portuguese side.

<img width="1550" alt="screen shot 2018-02-13 at 4 59 19 pm" src="https://user-images.githubusercontent.com/252276/36176108-8da25eb0-10df-11e8-9151-571790c02acf.png">

**Comment by jhmullen** [comment]
fixed this in 98a09979ae571968684699a108fff58c22f34b8d
