### ISSUE TITLE
Design flagged content admin panel

### ISSUE THREAD

**Issue by jhmullen** [Datawheel/codelife#353]
On the branch `feature-discussion`, the Admin Panel has a Report Viewer tab.  At Dave's request, I put the entire comment/thread itself IN the report viewer so the Admin can view it and judge it then and there.

However, there is now a big undesigned discussion thread in the report viewer, which will need to be designed to fit.

**Comment by jhmullen** [comment]
Moving this from @davelandry to @perpetualgrimace.  Note that this is now in mainline `develop` and not the feature branch.

**Comment by perpetualgrimace** [comment]
Styled discussion board in 1e043001, 7948edae; styled flagged content admin panel in 10d94966.
