### ISSUE TITLE
[mobile design] island homes needs responsive love

### ISSUE THREAD

**Issue by alexandersimoes** [Datawheel/codelife#359]
island is too small to accommodate horizontal levels
![img_7158](https://user-images.githubusercontent.com/252276/36999791-3bca903e-208f-11e8-9b42-647066bf74b3.JPG)

next/previous islands overlap
![img_7159](https://user-images.githubusercontent.com/252276/36999730-10508ab2-208f-11e8-958f-0a5b73f939d3.JPG)

**Comment by perpetualgrimace** [comment]
I will be expecting one issue for every page on the site 😉

**Comment by perpetualgrimace** [comment]
Commit 3fa4519b addresses the first bit.

**Comment by perpetualgrimace** [comment]
3fa4519b addresses the first bit:

![codelife-responsive-island-path](https://user-images.githubusercontent.com/6193798/37116899-95eb645a-221d-11e8-91b4-04d9d3a4bd35.gif)

**Comment by alexandersimoes** [comment]
Good stuff! I'll wait for tomorrows dev release, test it on an actual device and then close.

**Comment by perpetualgrimace** [comment]
3b712e4 takes it the rest of the way:
![codelife-responsive-island-level](https://user-images.githubusercontent.com/6193798/37182911-9bfad24c-2301-11e8-8cc6-0a88406e7114.gif)
