### ISSUE TITLE
[mobile design] next/previous button exceptions

### ISSUE THREAD

**Issue by alexandersimoes** [Datawheel/codelife#360]
If next is grayed out:
![img_7160](https://user-images.githubusercontent.com/252276/36999869-7f5bc5f2-208f-11e8-8b99-6019bc9cef0e.JPG)

if you're on the first slide
![img_7162](https://user-images.githubusercontent.com/252276/36999967-c94c32e6-208f-11e8-9cb6-49dc8078f0a5.JPG)

**Comment by perpetualgrimace** [comment]
Addressed in #0ffb0488
