### ISSUE TITLE
[mobile design] weird styling on last slide action buttons

### ISSUE THREAD

**Issue by alexandersimoes** [Datawheel/codelife#361]
![img_7161](https://user-images.githubusercontent.com/252276/37000018-f043960a-208f-11e8-890c-d57bc6f6b275.JPG)

**Comment by perpetualgrimace** [comment]
I took a crack at this one last week, had a difficult time splitting the return to island and next level buttons apart (they're currently wrapped in a div). Will bug @jhmullen about this next time I'm in the office.

**Comment by jhmullen** [comment]
pushed a small fix in 7c089a9789b8327e661362c4d6f906b27f445780 that getes around this
