### ISSUE TITLE
Reset password form is unstyled

### ISSUE THREAD

**Issue by perpetualgrimace** [Datawheel/codelife#370]
![reset password form 2x](https://user-images.githubusercontent.com/6193798/37366417-c694db64-26d6-11e8-9eca-8024043596f4.png)

NOTE: There's also no confirmation screen.

**Comment by perpetualgrimace** [comment]
As of commit 6c18a5e2 it's styled. 

Still no feedback though, even though that seems to be built into canon. @davelandry?

![reset-password 2x](https://user-images.githubusercontent.com/6193798/37855984-5bc05ecc-2ec8-11e8-84bc-967aeebf6e21.png)

**Comment by davelandry** [comment]
@perpetualgrimace what do you mean by feedback?

[This line](https://github.com/Datawheel/codelife/blob/develop/app/components/PasswordReset.jsx#L70-L72) is what should be happening when a password is reset successfully.

**Comment by perpetualgrimace** [comment]
@davelandry No toasts are displayed, and it seems like the page does a hard reset.

**Comment by perpetualgrimace** [comment]
Leaving this one closed since the style is done, opened new issue #395 for the hard refresh / no toast bug.
