### ISSUE TITLE
Contest page design

### ISSUE THREAD

**Issue by perpetualgrimace** [Datawheel/codelife#371]
## Design
- [x] design contest page
- [x] design contest sign up dialog
- [x] design project submission dialog

## CSS
- [x] implement contest page design
- [x] implement contest sign up dialog design
- [x] implement project submission dialog design

**Comment by jhmullen** [comment]
@perpetualgrimace Please note that ContestSignup.jsx and ContestSubmit.jsx will need design too - not sure if you want those to be in this issue or another.

**Comment by perpetualgrimace** [comment]
Done, aside from a few minor bugs with the signup form. Opened issue #404 for those, closing this one.
