### ISSUE TITLE
Update IslandEditor and style.yml to work together properly

### ISSUE THREAD

**Issue by jhmullen** [Datawheel/codelife#372]
IslandEditor.jsx depends on style.yml to skin islands.  

In the old style.yml, I was able to map over `styleyml.islands` to get a list of available themes, and use these to populate a dropdown with color swatches.

However, the new style.yml doesn't have these separate entities, and only has elements like `desert-island-dark`.

James:
- [x] Add a map object to style.yml with the root words like `jungle` and `themepark` that I can map over and append `-dark`, `-medium` and `-light` for the swatches

Jimmy:
- [x] Update IslandEditor.jsx to populate its dropdown based on this new format

**Comment by perpetualgrimace** [comment]
@jhmullen will this work?

<img width="1078" alt="screen shot 2018-03-14 at 3 58 03 pm" src="https://user-images.githubusercontent.com/6193798/37427710-95aa651c-27a0-11e8-9e35-14377aacb40e.png">

**Comment by perpetualgrimace** [comment]
Just pushed #14d81587. Admin island pages are at least loading in now. 😄
