### ISSUE TITLE
Co-op projects design

### ISSUE THREAD

**Issue by perpetualgrimace** [Datawheel/codelife#402]
- [x] mock up manage co-ops dialog
- [x] implement manage co-ops dialog
- [x] make co-ops dialog responsive

**Comment by jhmullen** [comment]
To add to the design considerations, please take note that you may now leave a project:

<img width="378" alt="screen shot 2018-04-03 at 9 05 10 pm" src="https://user-images.githubusercontent.com/1714292/38283203-c070a04e-3782-11e8-878a-81dc772b8e0b.png">

<img width="465" alt="screen shot 2018-04-03 at 9 05 16 pm" src="https://user-images.githubusercontent.com/1714292/38283209-c4834542-3782-11e8-8516-2d640a8503ba.png">

**Comment by perpetualgrimace** [comment]
Design implemented as of commit 8abf31e4

**Comment by perpetualgrimace** [comment]
Fully responsive as of commit 195e17b0.

As for the project studio sidebar actions, I'm going to roll that up into issue #364.
