### ISSUE TITLE
Home —  logged-out content renders, then re-renders logged-in content

### ISSUE THREAD

**Issue by perpetualgrimace** [Datawheel/codelife#413]
![home-page-loggedout-flash](https://user-images.githubusercontent.com/6193798/38878425-e9756bbc-422e-11e8-96b9-11b1b3260b05.gif)

Slack conversation:
https://datawheel.slack.com/archives/G1D4GV86B/p1523975377000393

**Comment by jhmullen** [comment]
I added a loading state so the underlying content doesn't flash the non-logged in.  There is still a "blip" as the React app remounts but AFAIK this is a known issue
