### ISSUE TITLE
Profile Page Revamp

### ISSUE THREAD

**Issue by jhmullen** [Datawheel/codelife#42]
Profile page will need to be revamped.  This includes:

- [x] Profile Picture upload 
- [x] Form for writing bio
- [ ] ~Display of badges based on completion (dbtable: userprogress)~
- [ ] ~"Resume" components~
- [ ] ~Coin totals~
- [x] List of Codeblocks/Projects

**Comment by davelandry** [comment]
closing in favor of #213 and #214
