### ISSUE TITLE
Lessonplan — error on initial load

### ISSUE THREAD

**Issue by perpetualgrimace** [Datawheel/codelife#420]
It seems to trigger only once during a session. Logging in/out and heading to `lessonplan` triggers it again.

<img width="789" alt="screen shot 2018-04-30 at 2 00 56 pm" src="https://user-images.githubusercontent.com/6193798/39442395-0695748a-4c7f-11e8-9c21-e064aa1f1493.png">

**Comment by jhmullen** [comment]
I'm unable to reproduce this, can we have a look at this tomorrow?

**Comment by jhmullen** [comment]
This was fixed by changing the wrapper of App.jsx from <div> to <Canon>
