### ISSUE TITLE
Design Share Link Island Interstitial

### ISSUE THREAD

**Issue by jhmullen** [Datawheel/codelife#425]
When you beat an island the first time, a popover comes up encouraging you to go to the next island.  I recently added a "Share on Facebook" button to this that needs styling.

Swap the commenting on lines 128/129 of CodeBlockEditor.jsx to test the popover on every save.

**Comment by perpetualgrimace** [comment]
addressed in 6d647789

**Comment by perpetualgrimace** [comment]
Note to self: add body text back to the dialog
