### ISSUE TITLE
Hidden user profile displays a loading screen

### ISSUE THREAD

**Issue by perpetualgrimace** [Datawheel/codelife#436]
Possible alternative (better) behaviors:
- Redirect to homepage
- Display 404 page
- Display "this profile is private" message

Related question:
Currently, we're only showing the profile visibility toggle for admin users. Should we also allow normal users to toggle this option for their own profile?

**Comment by jhmullen** [comment]
I updated this in a previous commit, attempting to hit profiles while not logged in now redirects to `/`.

The toggle is not for visibility of the profile - it is for visibility of this student's codeblocks and projects.  It is only used by Admins to "mass-ban" someone who has a history of creating bad content (Disabling their projects/codeblocks from being seen publicly)

There are currently no plans for Profile public/private setting for individual users, though it could be put on the roadmap.
