### ISSUE TITLE
Add Facebook Spinner for Image Processing

### ISSUE THREAD

**Issue by jhmullen** [Datawheel/codelife#441]
Projects, IslandLevel, and CodeBlockEditor now have a state variable called `canPostToFacebook` which runs on a timeout.  

Please stylize Facebook buttons with a "processing" spinner of some kind, and release it when `canPostToFacebook` comes back around to true.

**Comment by perpetualgrimace** [comment]
@jhmullen this is in place and styled, but as far as I can tell `canPostToFacebook` always returns `true`.
