### ISSUE TITLE
Admin — Make Preview window wider

### ISSUE THREAD

**Issue by alexandersimoes** [Datawheel/codelife#469]
Right now previewing the content in the lesson builder is very small and hard to use:

![screen shot 2018-06-12 at 12 55 12 pm](https://user-images.githubusercontent.com/252276/41305167-0e6f3e4c-6e40-11e8-8571-cfe6ad15cea4.png)

**Comment by perpetualgrimace** [comment]
@alexandersimoes FYI: add the class `is-fullscreen` to any Dialog and it'll fill up the whole dang screen.
