### ISSUE TITLE
Diagram — flex box diagram needed

### ISSUE THREAD

**Issue by alexandersimoes** [Datawheel/codelife#470]
Take a look here: https://codelife.com/admin/lesson-builder/island-bacb/level-1145/slide-ddee

Here are the 2 inspirations from Nick: 
https://cdn.css-tricks.com/wp-content/uploads/2013/04/justify-content-2.svg
https://cdn.css-tricks.com/wp-content/uploads/2014/05/align-items.svg

**Comment by davelandry** [comment]
Added to the live CMS on codelife.com, needs to be committed to the repository from the server by @alexandersimoes:

![flex - en](https://user-images.githubusercontent.com/1847581/41357235-b12cb4ee-6ef3-11e8-8ce7-9a59302538e6.jpg)
