### ISSUE TITLE
Admin — overlapping in CMS dialog for adding links

### ISSUE THREAD

**Issue by alexandersimoes** [Datawheel/codelife#471]
![screen shot 2018-06-12 at 1 15 52 pm](https://user-images.githubusercontent.com/252276/41306060-eb75149a-6e42-11e8-99d9-0e8b6192115d.png)

**Comment by perpetualgrimace** [comment]
<img width="492" alt="screen shot 2018-06-12 at 6 15 08 pm" src="https://user-images.githubusercontent.com/6193798/41320151-97c497ec-6e6c-11e8-8675-cb7569675d7c.png">

![image](https://user-images.githubusercontent.com/6193798/41320169-ae2642c4-6e6c-11e8-9264-c4c0304a3452.png)
