### ISSUE TITLE
Diagram — @font-face diagram needed 

### ISSUE THREAD

**Issue by alexandersimoes** [Datawheel/codelife#472]
https://codelife.com/admin/lesson-builder/island-bacb/level-e486/slide-06d7

Nick's request: image of code example using @font-face: https://i.stack.imgur.com/zyoQB.png

**Comment by davelandry** [comment]
Added to the live CMS on codelife.com, needs to be committed to the repository from the server by @alexandersimoes:

![font-face](https://user-images.githubusercontent.com/1847581/41357927-41538236-6ef5-11e8-957c-7aadc2fc6f54.jpg)
