### ISSUE TITLE
Diagram — semantic website heirarchy diagram needed 

### ISSUE THREAD

**Issue by alexandersimoes** [Datawheel/codelife#473]
https://codelife.com/admin/lesson-builder/island-bacb/level-e486/slide-accc

website with lorem ipsum with a headline, subhead, and body text labeled, like this diagram: https://cdn.designcrowd.com/blog/2016/April/hierarchy-of-text/Newspaper_828x500.png

**Comment by davelandry** [comment]
Added to the live CMS on codelife.com, needs to be committed to the repository from the server by @alexandersimoes:

![hierarchy - en](https://user-images.githubusercontent.com/1847581/41358508-80e7f228-6ef6-11e8-865a-7099fb9b6be3.jpg)
![hierarchy - pt](https://user-images.githubusercontent.com/1847581/41358509-80f6de50-6ef6-11e8-8728-9409895da6b7.jpg)

**Comment by alexandersimoes** [comment]
Suggested changes from Renato:

"Bem-vind@" instead of "Bem Vinda"; and "corpo dO texto" instead of "corpo dE texto"

**Comment by davelandry** [comment]
@alexandersimoes done! just needs your push/commit from the server
