### ISSUE TITLE
Diagram — signup box error screenshot needed 

### ISSUE THREAD

**Issue by alexandersimoes** [Datawheel/codelife#474]
https://codelife.com/admin/lesson-builder/island-bacb/level-45be/slide-27c9

screenshot of the facebook signup form with errors: http://blog.usabilla.com/wp-content/uploads/2015/11/Screen-Shot-2017-01-17-at-16.18.50.png

**Comment by davelandry** [comment]
Added to the live CMS on codelife.com, needs to be committed to the repository from the server by @alexandersimoes:

<img width="448" alt="screen shot 2018-06-13 at 10 45 11 am" src="https://user-images.githubusercontent.com/1847581/41358749-0b67b2ee-6ef7-11e8-816c-f5fbda683831.png">
<img width="447" alt="screen shot 2018-06-13 at 10 45 33 am" src="https://user-images.githubusercontent.com/1847581/41358750-0b7a9ea4-6ef7-11e8-9986-9dd821ff7ee9.png">
