### ISSUE TITLE
Diagram — Apple website screenshot needed 

### ISSUE THREAD

**Issue by alexandersimoes** [Datawheel/codelife#475]
https://codelife.com/admin/lesson-builder/island-bacb/level-45be/slide-7670

screenshot of the apple website: https://images.thoughtbot.com/cp-design-for-the-web/rioTUswbSSC4PZBrq0Kv_elements-white-space-macro.png

**Comment by davelandry** [comment]
Added to the live CMS on codelife.com, needs to be committed to the repository from the server by @alexandersimoes:

![screen shot 2018-06-13 at 10 50 34 am](https://user-images.githubusercontent.com/1847581/41359218-04e68796-6ef8-11e8-90ef-e78faab5b79a.jpg)
![screen shot 2018-06-13 at 10 49 53 am](https://user-images.githubusercontent.com/1847581/41359219-04f926c6-6ef8-11e8-8bd3-40ce64332885.jpg)
