### ISSUE TITLE
Diagram — design contrast diagram needed 

### ISSUE THREAD

**Issue by alexandersimoes** [Datawheel/codelife#476]
https://codelife.com/admin/lesson-builder/island-bacb/level-45be/slide-0be9

image of black text on white background and image of light pink text on a light blue background

**Comment by davelandry** [comment]
Added to the live CMS on codelife.com, needs to be committed to the repository from the server by @alexandersimoes:

![contrast - en](https://user-images.githubusercontent.com/1847581/41368158-1809734e-6f0f-11e8-99fa-c7f4e0612de1.jpg)
![contrast - pt](https://user-images.githubusercontent.com/1847581/41368159-181851b6-6f0f-11e8-8dde-a7a60ee5b089.jpg)
