### ISSUE TITLE
Diagram — color scheme diagram needed 

### ISSUE THREAD

**Issue by alexandersimoes** [Datawheel/codelife#477]
https://codelife.com/admin/lesson-builder/island-bacb/level-45be/slide-41bc

diagrams of color schemes, like there:
http://www.worqx.com/color/combinations.htm

**Comment by davelandry** [comment]
Added to the live CMS on codelife.com, needs to be committed to the repository from the server by @alexandersimoes:

![color - en](https://user-images.githubusercontent.com/1847581/41369803-e95e63f6-6f13-11e8-8349-de84c17feec5.jpg)
![color - pt](https://user-images.githubusercontent.com/1847581/41369804-e96b480a-6f13-11e8-87da-7bf3b8a29c63.jpg)
