### ISSUE TITLE
Diagram — color wheel diagram needed 

### ISSUE THREAD

**Issue by alexandersimoes** [Datawheel/codelife#478]
https://codelife.com/admin/lesson-builder/island-bacb/level-45be/slide-2e6c

image of the color wheel with primary, secondary, and tertiary colors labeled

**Comment by davelandry** [comment]
Added to the live CMS on codelife.com, needs to be committed to the repository from the server by @alexandersimoes:

![wheel - en](https://user-images.githubusercontent.com/1847581/41370120-c576d008-6f14-11e8-9f5b-71765b443ec3.jpg)
![wheel - pt](https://user-images.githubusercontent.com/1847581/41370122-c589046c-6f14-11e8-977f-b869554d2a9c.jpg)
