### ISSUE TITLE
Diagram — indentation diagram needed 

### ISSUE THREAD

**Issue by alexandersimoes** [Datawheel/codelife#480]
https://codelife.com/admin/lesson-builder/island-bacb/level-fdba/slide-77cb

Screenshot of nested html elements with the parent element, indentation, and child element labeled

**Comment by alexandersimoes** [comment]
suggested changes from renato:

"espaço" instead of "indent"; and "filho" instead of "criança"

**Comment by davelandry** [comment]
@alexandersimoes fixed! just needs your push commit from the server
