### ISSUE TITLE
Facebook share giving boilerplate description text

### ISSUE THREAD

**Issue by alexandersimoes** [Datawheel/codelife#491]
When sharing a project on facebook the share dialog says "Description of CodeLife". I think we should either remove that field or put something a little better.

![screen shot 2018-07-16 at 1 20 57 pm](https://user-images.githubusercontent.com/252276/42825952-3ad1cd56-89b1-11e8-87b1-dddfdd6b118d.png)

**Comment by davelandry** [comment]
(@alexandersimoes btw this example is amazing, can I call dibs?)
