### ISSUE TITLE
Quick content improvements

### ISSUE THREAD

**Issue by perpetualgrimace** [Datawheel/codelife#507]
- [x] island 1: provide an example image URL so mobile users don't switch tabs and never come back
- [x] island 1: remove test slide (dev server only)
- [x] `h1-h3` instead of `h1-h6` for the first codeblock
- [x] add recommendation to install & use mobile keyboards more suited for coding (i.e., [‎DevKey for iOS](https://itunes.apple.com/us/app/devkey-developer-keyboard-for-programming/id961304986?mt=8) and [K:Code for Android](https://play.google.com/store/apps/details?id=com.keilyn3d.kcode))

**Comment by alexandersimoes** [comment]
With the latest release, I also added that new slide recommending users download a mobile dev keyboard.
