### ISSUE TITLE
JS console disappears on mobile

### ISSUE THREAD

**Issue by alexandersimoes** [Datawheel/codelife#514]
In the later islands when the user is asked to write JS w/ console statements like this level:
/island/island-9e30/level-7088/slide-d434

Clicking the console on mobile makes it disappear.

![img_2028d3af1cf2-1](https://user-images.githubusercontent.com/252276/46539943-eb60df00-c885-11e8-94de-441de76d3a0f.jpeg)

**Comment by perpetualgrimace** [comment]
![image](https://user-images.githubusercontent.com/6193798/46763420-c4e8dc80-cca7-11e8-8793-3c849bc05688.png)
