### ISSUE TITLE
Style Email popover

### ISSUE THREAD

**Issue by jhmullen** [Datawheel/codelife#525]
On the `develop` branch, an interstitial has been added to prompt social users for their email address.  This popover needs design work.

In IslandLevel.jsx, override the `checkpointEmailOpen` state variable to be `true` in order to manually show the popup.

**Comment by perpetualgrimace** [comment]
Appreciate the debug directions :)

**Comment by perpetualgrimace** [comment]
Styled in 8ffcb414
